### ISSUE TITLE
Cannot find module 'puppeteer'

### ISSUE THREAD

**Issue by apospa** [soyrubio/MMM-idos#4]
Hello, after pasting module to config i get only black screen. Please can You help me what am I doing wrong? Thank You 

/MagicMirror $ npm run start

> magicmirror@2.20.0 start
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[03.09.2022 21:10.14.347] [LOG]   Starting MagicMirror: v2.20.0
[03.09.2022 21:10.14.354] [LOG]   Loading config ...
[03.09.2022 21:10.14.362] [LOG]   Loading module helpers ...
[03.09.2022 21:10.14.366] [LOG]   No helper found for module: alert.
[03.09.2022 21:10.14.385] [LOG]   Initializing new module helper ...
[03.09.2022 21:10.14.387] [LOG]   Module helper loaded: updatenotification
[03.09.2022 21:10.14.388] [LOG]   No helper found for module: clock.
[03.09.2022 21:10.14.587] [LOG]   Initializing new module helper ...
[03.09.2022 21:10.14.588] [LOG]   Module helper loaded: calendar
[03.09.2022 21:10.14.589] [LOG]   No helper found for module: compliments.
[03.09.2022 21:10.14.590] [LOG]   No helper found for module: weather.
[03.09.2022 21:10.14.611] [LOG]   Initializing new module helper ...
[03.09.2022 21:10.14.611] [LOG]   Module helper loaded: newsfeed
[03.09.2022 21:10.14.616] [ERROR] WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'puppeteer'
Require stack:
- /home/pi/MagicMirror/modules/MMM-idos/node-idos.js
- /home/pi/MagicMirror/modules/MMM-idos/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
[03.09.2022 21:10.14.617] [LOG]   Loading module helpers ...
[03.09.2022 21:10.14.618] [LOG]   No helper found for module: alert.
[03.09.2022 21:10.14.619] [LOG]   Initializing new module helper ...
[03.09.2022 21:10.14.619] [LOG]   Module helper loaded: updatenotification
[03.09.2022 21:10.14.621] [LOG]   No helper found for module: clock.
[03.09.2022 21:10.14.621] [LOG]   Initializing new module helper ...
[03.09.2022 21:10.14.622] [LOG]   Module helper loaded: calendar
[03.09.2022 21:10.14.623] [LOG]   No helper found for module: compliments.
[03.09.2022 21:10.14.624] [LOG]   No helper found for module: weather.
[03.09.2022 21:10.14.625] [LOG]   Initializing new module helper ...
[03.09.2022 21:10.14.626] [LOG]   Module helper loaded: newsfeed
[03.09.2022 21:10.14.628] [ERROR] App threw an error during load
[03.09.2022 21:10.14.630] [ERROR] Error: Cannot find module 'puppeteer'
Require stack:
- /home/pi/MagicMirror/modules/MMM-idos/node-idos.js
- /home/pi/MagicMirror/modules/MMM-idos/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-idos/node-idos.js:12:19)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
[03.09.2022 21:10.14.632] [ERROR] Whoops! There was an uncaught exception...
[03.09.2022 21:10.14.637] [ERROR] Error: Cannot find module 'puppeteer'
Require stack:
- /home/pi/MagicMirror/modules/MMM-idos/node-idos.js
- /home/pi/MagicMirror/modules/MMM-idos/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-idos/node-idos.js:12:19)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-idos/node-idos.js',
    '/home/pi/MagicMirror/modules/MMM-idos/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
[03.09.2022 21:10.14.639] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[03.09.2022 21:10.14.640] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[03.09.2022 21:10.14.889] [LOG]   Launching application.
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open kms_swrast: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load swrast driver

**Comment by apospa** [comment]
sorry, my bad. Fixed it already.
